
services:
  web:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../backend:/app/backend
      - ../../main.py:/app/main.py
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5432/${DATABASE_NAME}
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST=${DATABASE_HOST}

  redis:
    image: redis:7.2.2-alpine
    restart: always
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data

volumes:
  postgres_data: