import os

REDIS_SERVER_HOST = os.environ['REDIS_SERVER_HOST']
REDIS_SERVER_PORT = os.environ['REDIS_SERVER_PORT']
REDIS_SERVER_PASSWORD = os.environ['REDIS_SERVER_PASSWORD']
# REDIS_SERVER_DEFAULT_TTL = os.environ['REDIS_SERVER_DEFAULT_TTL']

DATABASE_USERNAME = os.environ['DATABASE_USERNAME']
DATABASE_PASSWORD = os.environ['DATABASE_PASSWORD']
DATABASE_HOST = os.environ['DATABASE_HOST']
DATABASE_PORT = os.environ['DATABASE_PORT']
DATABASE_NAME = os.environ['DATABASE_NAME']