import os
from dotenv import load_dotenv

load_dotenv()

REDIS_SERVER_HOST = os.getenv("REDIS_SERVER_HOST")
REDIS_SERVER_PORT = os.getenv("REDIS_SERVER_PORT")
REDIS_SERVER_PASSWORD = os.getenv("REDIS_SERVER_PASSWORD")
REDIS_URL = os.getenv("REDIS_URL", "redis://red-crvu9mpu0jms73due760:6379")
# REDIS_SERVER_DEFAULT_TTL = os.getenv('REDIS_SERVER_DEFAULT_TTL')

DATABASE_USERNAME = os.getenv("DATABASE_USERNAME")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_PORT = os.getenv("DATABASE_PORT")
DATABASE_NAME = os.getenv("DATABASE_NAME")
